services:
  petsnode:
    build:
      context: .
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: pets
    ports:
      - 3000:3000
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pets
    ports:
      - 3366:3306

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal



